annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/kube-version: '>= 1.25.0-0 < 1.31.0-0'
  catalog.cattle.io/namespace: cattle-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux
  catalog.cattle.io/rancher-version: '>= 2.9.0-0 < 2.10.0-0'
  catalog.cattle.io/release-name: rancher-cce-operator-crd
apiVersion: v2
appVersion: 0.5.0-rc3
description: CCE Operator CustomResourceDefinitions
name: rancher-cce-operator-crd
version: 104.0.0+up0.5.0-rc3
