global:
  systemDefaultRegistry: ""

tkeOperator:
  image:
    repository: cnrancher/tke-operator
    tag: v2.9.1-ent

httpProxy: ""
httpsProxy: ""
noProxy: ""
additionalTrustedCAs: false
lockName: ""
lockNamespace: ""
qps: ""
burst: ""
