apiVersion: v2
appVersion: 3.5.0
description: A Helm chart for DCGM exporter
home: https://github.com/nvidia/dcgm-exporter/
icon: https://assets.nvidiagrid.net/ngc/logos/DCGM.png
keywords:
- gpu
- cuda
- compute
- monitoring
- telemetry
- tesla
kubeVersion: '>= 1.19.0-0'
name: dcgm-exporter
sources:
- https://github.com/nvidia/dcgm-exporter
version: 3.5.0
